# Final Project Tasks

# 1. Dataset Selection and Description

💾 Dataset Description:
Data Source: MovieLens (provided by GroupLens)
- This data has been cleaned up - users
who had less than 20 ratings or did not have complete demographic
information were removed from this data set

1. Data Format:
- The *.dat files are plain text files, with :: (double colons) as the delimiter.
- 100000 ratings by 943 users on 1682 items. Each user has rated at least 20 movies. Users and items are numbered consecutively from 1. The data is randomly ordered.

2. Structured Data:

- Movies data is display as follows: Movie_Id | Movie_Title | Release_Date | Video_Release_Date | Imdb_Url | All the genres...  
The last 19 fields are the genres, a 1 indicates the movieis of that genre, a 0 indicates it is not; movies can be in several genres at once.
    
- Ratings data is display as follows: UserID | Movie_Id | Rating | Timestamp

- Users data is display as follows: UserID | Gender | Age | Occupation | Zip-code 

3. Sample Business Questions:

- Which movies are the most popular among different age groups?

- Do male and female users have different rating preferences?

- Which movie genres have the highest average ratings?

- Movies rated per user occupation?

# 0. Transforming the Data to csv file.

The files creation lines are commented since they only need to be run once.

In [32]:
''' For u.data to u_ratings_clean.csv '''

df_ratings = pd.read_csv('u.data', sep='\s+', names=['UserID', 'ItemID', 'Rating', 'Timestamp'])
# df_ratings.to_csv('u_ratings_clean.csv', sep=',', index=False)  
# df_ratings


''' For u.user u_users_clean.csv '''

df_user = pd.read_csv('u.user', sep='|', names=['UserID', 'Age', 'Gender', 'Occupation', 'Zip_Code'])
# df_user.to_csv('u_users_clean.csv', sep=',', index=False)
# df_user


''' For u.item to u_movies_clean.csv '''

features = ("movie id | movie title | release date | video release date | "
            "IMDb URL | unknown | Action | Adventure | Animation | "
            "Children | Comedy | Crime | Documentary | Drama | Fantasy | "
            "Film-Noir | Horror | Musical | Mystery | Romance | Sci-Fi | "
            "Thriller | War | Western")
features = [word.title().replace(" ","_") for word in features.split(' | ')]

df_movies = pd.read_csv('u.item', sep='|', names=features, encoding='latin-1')
# df_movies.to_csv('u_movies_clean.csv', sep=',', index=False)
# df_movies

# 1. Pre-processing Data and Some Statistics

In [2]:
import pandas as pd
import numpy as np
import os

## Users Data

In [3]:
# Load the DataSet
users = pd.read_csv("u_users_clean.csv")
users = pd.DataFrame(users)
users

     UserID  Age Gender     Occupation Zip_Code
0         1   24      M     technician    85711
1         2   53      F          other    94043
2         3   23      M         writer    32067
3         4   24      M     technician    43537
4         5   33      F          other    15213
..      ...  ...    ...            ...      ...
938     939   26      F        student    33319
939     940   32      M  administrator    02215
940     941   20      M        student    97229
941     942   48      F      librarian    78209
942     943   22      M        student    77841

[943 rows x 5 columns]

In [4]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   UserID      943 non-null    int64
 1   Age         943 non-null    int64
 2   Gender      943 non-null    object
 3   Occupation  943 non-null    object
 4   Zip_Code    943 non-null    object
dtypes: int64(2), object(3)
memory usage: 37.0+ KB

In [5]:
round(users.describe(), 3)

        UserID      Age
count  943.000  943.000
mean   472.000   34.052
std    272.365   12.193
min      1.000    7.000
25%    236.500   25.000
50%    472.000   31.000
75%    707.500   43.000
max    943.000   73.000

There is one kid in among the users:

In [6]:
users[users.Age <= 12]

     UserID  Age Gender Occupation Zip_Code
29       30    7      M    student    55436
288     289   11      M       none    94619
470     471   10      M    student    77459

In [7]:
# Summary for categorical columns
users.describe(include=['object'])

       Gender Occupation Zip_Code
count     943        943      943
unique      2         21      795
top         M    student    55414
freq      670        196        9

In [8]:
users['Occupation'].unique()

array(['technician', 'other', 'writer', 'executive', 'administrator',
       'student', 'lawyer', 'educator', 'scientist', 'entertainment',
       'programmer', 'librarian', 'homemaker', 'artist', 'engineer',
       'marketing', 'none', 'healthcare', 'retired', 'salesman', 'doctor'],
      dtype=object)

#### Zip_Code is not needed. We can drop it:

In [11]:
users2 = users.drop('Zip_Code', axis = 1)
users2.columns

Index(['UserID', 'Age', 'Gender', 'Occupation'], dtype='object')

#### Users per occupation:

In [12]:
users2.Occupation.value_counts()

student          196
other            105
educator          95
administrator     79
engineer          67
programmer        66
librarian         51
writer            45
executive         32
scientist         31
artist            28
technician        27
marketing         26
entertainment     18
healthcare        16
retired           14
lawyer            12
salesman          12
none               9
homemaker          7
doctor             7
Name: Occupation, dtype: int64

## Ratings Data

In [13]:
# Load the DataSet
ratings = pd.read_csv("u_ratings_clean.csv")
ratings = pd.DataFrame(ratings)

ratings.rename(columns={'ItemID':'Movie_Id'}) # Rename properly to match the other tables.

       UserID  Movie_Id  Rating  Timestamp
0         196       242       3  881250949
1         186       302       3  891717742
2          22       377       1  878887116
3         244        51       2  880606923
4         166       346       1  886397596
...       ...       ...     ...        ...
99995     880       476       3  880175444
99996     716       204       5  879795543
99997     276      1090       1  874795795
99998      13       225       2  882399156
99999      12       203       3  879959583

[100000 rows x 4 columns]

In [14]:
ratings.duplicated(subset=['UserID','ItemID']).any()

False

In [15]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   UserID     100000 non-null  int64
 1   ItemID     100000 non-null  int64
 2   Rating     100000 non-null  int64
 3   Timestamp  100000 non-null  int64
dtypes: int64(4)
memory usage: 3.1 MB

In [16]:
round(ratings.describe(), 2)

          UserID     ItemID     Rating     Timestamp
count  100000.00  100000.00  100000.00  1.000000e+05
mean      462.48     425.53       3.53  8.835289e+08
std       266.61     330.80       1.13  5.343856e+06
min         1.00       1.00       1.00  8.747247e+08
25%       254.00     175.00       3.00  8.794487e+08
50%       447.00     322.00       4.00  8.828269e+08
75%       682.00     631.00       4.00  8.882600e+08
max       943.00    1682.00       5.00  8.932866e+08

In [17]:
ratings2 = ratings.drop('Timestamp', axis=1)
ratings2.columns

Index(['UserID', 'ItemID', 'Rating'], dtype='object')

## Movies Data

In [18]:
# Load the DataSet
movies = pd.read_csv("u_movies_clean.csv", parse_dates=["Release_Date"]) # Load with date format optimized for pandas.
movies = pd.DataFrame(movies)
# data.Release_Date = data.Release_Date.dt.date # date format without time (year/month/day) and compatible with json.
movies

,Movie_Id,Movie_Title,Release_Date,Video_Release_Date,Imdb_Url,Unknown,Action,Adventure,Animation,Children,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),1995-01-01,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),1995-01-01,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),1995-01-01,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),1995-01-01,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),1995-01-01,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,1678,Mat' i syn (1997),1998-02-06,NaN,http://us.imdb.com/M/title-exact?Mat%27+i+syn+...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1678,1679,B. Monkey (1998),1998-02-06,NaN,http://us.imdb.com/M/title-exact?B%2E+Monkey+(...,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
1679,1680,Sliding Doors (1998),1998-01-01,NaN,http://us.imdb.com/Title?Sliding+Doors+(1998),0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1680,1681,You So Crazy (1994),1994-01-01,NaN,http://us.imdb.com/M/title-exact?You%20So%20Cr...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1681,1682,Scream of Stone (Schrei aus Stein) (1991),1996-03-08,NaN,http://us.imdb.com/M/title-exact?Schrei%20aus%...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [19]:
movies.Movie_Id.duplicated().any()  # Check if there is any duplicated ID.

False

In [20]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1682 entries, 0 to 1681
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Movie_Id            1682 non-null   int64
 1   Movie_Title         1682 non-null   object
 2   Release_Date        1681 non-null   datetime64[ns]
 3   Video_Release_Date  0 non-null      float64
 4   Imdb_Url            1679 non-null   object
 5   Unknown             1682 non-null   int64
 6   Action              1682 non-null   int64
 7   Adventure           1682 non-null   int64
 8   Animation           1682 non-null   int64
 9   Children            1682 non-null   int64
 10  Comedy              1682 non-null   int64
 11  Crime               1682 non-null   int64
 12  Documentary         1682 non-null   int64
 13  Drama               1682 non-null   int64
 14  Fantasy             1682 non-null   int64
 15  Film-Noir           1682 non-null   int64
 16  Horror              1682 non-null   int64
 17  Musical             1682 non-null   int64
 18  Mystery             1682 non-null   int64
 19  Romance             1682 non-null   int64
 20  Sci-Fi              1682 non-null   int64
 21  Thriller            1682 non-null   int64
 22  War                 1682 non-null   int64
 23  Western             1682 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(20), object(2)
memory usage: 315.5+ KB

#### Imdb_Url is not needed and Video_Release_Date is empty. We can drop them:

In [21]:
movies2 = movies.drop(columns=['Video_Release_Date', 'Imdb_Url'], axis=1)
print(movies2.columns)

Index(['Movie_Id', 'Movie_Title', 'Release_Date', 'Unknown', 'Action',
       'Adventure', 'Animation', 'Children', 'Comedy', 'Crime', 'Documentary',
       'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery',
       'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western'],
      dtype='object')

#### There is one missing Release_Date in the data, let's see what is happening:

In [22]:
missing = movies2[movies2.Release_Date.isnull()]
print(missing.T)

                  266
Movie_Id          267
Movie_Title   unknown
Release_Date      NaT
Unknown             1
Action              0
Adventure           0
Animation           0
Children            0
Comedy              0
Crime               0
Documentary         0
Drama               0
Fantasy             0
Film-Noir           0
Horror              0
Musical             0
Mystery             0
Romance             0
Sci-Fi              0
Thriller            0
War                 0
Western             0

#### As this record is useless, we can delete it:

In [23]:
movies3 = movies2.drop(index = missing.index)
n = movies3.isnull().any().sum() # Checks if there is any missing value in the data.
print(f'{n} missing values were found in the whole frame')

0 missing values were found in the whole frame

In [24]:
movies3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1681 entries, 0 to 1681
Data columns (total 22 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Movie_Id      1681 non-null   int64
 1   Movie_Title   1681 non-null   object
 2   Release_Date  1681 non-null   datetime64[ns]
 3   Unknown       1681 non-null   int64
 4   Action        1681 non-null   int64
 5   Adventure     1681 non-null   int64
 6   Animation     1681 non-null   int64
 7   Children      1681 non-null   int64
 8   Comedy        1681 non-null   int64
 9   Crime         1681 non-null   int64
 10  Documentary   1681 non-null   int64
 11  Drama         1681 non-null   int64
 12  Fantasy       1681 non-null   int64
 13  Film-Noir     1681 non-null   int64
 14  Horror        1681 non-null   int64
 15  Musical       1681 non-null   int64
 16  Mystery       1681 non-null   int64
 17  Romance       1681 non-null   int64
 18  Sci-Fi        1681 non-null   int64
 19  Thriller      1681 non-null   int64
 20  War           1681 non-null   int64
 21  Western       1681 non-null   int64
dtypes: datetime64[ns](1), int64(20), object(1)
memory usage: 302.1+ KB

In [25]:
movies3[movies3.Unknown==1] # One not null record has Unknown genre, so we can leave it like that.

,Movie_Id,Movie_Title,Release_Date,Unknown,Action,Adventure,Animation,Children,Comedy,Crime,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
1372,1373,Good Morning (1971),1971-02-04,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### Some Statistics

In [26]:
round(movies3.describe(), 3)
# The value of the mean for each genre is equal to the proportion/rate (%) of movies that are in each genre.

,Movie_Id,Unknown,Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
count,1681.000,1681.000,1681.000,1681.000,1681.000,1681.000,1681.000,1681.000,1681.00,1681.000,1681.000,1681.000,1681.000,1681.000,1681.000,1681.000,1681.000,1681.000,1681.000,1681.000
mean,841.842,0.001,0.149,0.080,0.025,0.073,0.300,0.065,0.03,0.431,0.013,0.014,0.055,0.033,0.036,0.147,0.060,0.149,0.042,0.016
std,485.638,0.024,0.357,0.272,0.156,0.260,0.459,0.246,0.17,0.495,0.114,0.119,0.228,0.180,0.187,0.354,0.238,0.357,0.201,0.126
min,1.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
25%,422.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
50%,842.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
75%,1262.000,0.000,0.000,0.000,0.000,0.000,1.000,0.000,0.00,1.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
max,1682.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.00,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000

#### Total of movies per genre:

In [27]:
print(movies3.loc[:,'Unknown':'Western'].sum()) # One movie can belong to several genres.

Unknown          1
Action         251
Adventure      135
Animation       42
Children       122
Comedy         505
Crime          109
Documentary     50
Drama          725
Fantasy         22
Film-Noir       24
Horror          92
Musical         56
Mystery         61
Romance        247
Sci-Fi         101
Thriller       251
War             71
Western         27
dtype: int64

#### Dates:

In [28]:
np.sort(movies3.Release_Date.dt.year.unique())

array([1922, 1926, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938,
       1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949,
       1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960,
       1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971,
       1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982,
       1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993,
       1994, 1995, 1996, 1997, 1998], dtype=int64)

#### Count of movies released per year:

In [29]:
movies3.Release_Date.dt.year.value_counts().head(20)

1996    355
1997    286
1995    219
1994    214
1993    126
1998     65
1992     37
1990     24
1991     22
1989     15
1986     15
1982     13
1987     13
1981     12
1988     11
1958      9
1979      9
1940      8
1957      8
1980      8
Name: Release_Date, dtype: int64

### Final Clean Data to Work With:

In [ ]:
users_clean = users2
ratings_clean = ratings2
movies_clean = movies3

# 2. Data Storage and Preprocessing (MongoDB)

## import to mongodb

In [41]:
import pandas as pd
from pymongo import MongoClient

password = "password"

# Connect MongoDB Atlas 
client = MongoClient(f"mongodb+srv://changch23:{password}@cluster0.eisxg.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0")

# Create DB
db = client["movielens100k"]

In [9]:
# import u_user_clean.csv
df_users = pd.read_csv("u_user_clean.csv")
db.users.drop()  
db.users.insert_many(df_users.to_dict(orient="records"))
print(f"✅ users import {len(df_users)} rows")

# import u_movies_clean.csv
df_movies = pd.read_csv("u_movies_clean.csv")
db.movies.drop()
db.movies.insert_many(df_movies.to_dict(orient="records"))
print(f"✅ movies import {len(df_movies)} rows")

# import u_ratings_clean.csv
df_ratings = pd.read_csv("u_ratings_clean.csv")
db.ratings.drop()
db.ratings.insert_many(df_ratings.to_dict(orient="records"))
print(f"✅ ratings import {len(df_ratings)} rows")

✅ users import 943 rows
✅ movies import 1682 rows
✅ ratings import 100000 rows

In [55]:
# Query the total number of documents in each collection
print("📽️ movies:", db.movies.count_documents({}))
print("⭐ ratings:", db.ratings.count_documents({}))
print("👤 users:", db.users.count_documents({}))

📽️ movies: 1682
⭐ ratings: 100000
👤 users: 943

In [43]:
# Add index for speed up
db.ratings.create_index("UserID")       
db.ratings.create_index("ItemID")         
db.ratings.create_index("Rating")         

db.users.create_index("UserID")           # join rating
db.movies.create_index("Movie_Id")        # join rating

'Movie_Id_1'

In [51]:
#check index
print(db.ratings.index_information())

{'_id_': {'v': 2, 'key': [('_id', 1)]}, 'UserID_1': {'v': 2, 'key': [('UserID', 1)]}, 'ItemID_1': {'v': 2, 'key': [('ItemID', 1)]}, 'Rating_1': {'v': 2, 'key': [('Rating', 1)]}}

# 3. Data Analysis（Use MongoDB）

In [29]:
import pandas as pd
from pymongo import MongoClient
from collections import defaultdict
import statistics

# 將資料轉為 pandas DataFrame
df_users = pd.DataFrame(list(db.users.find()))
df_movies = pd.DataFrame(list(db.movies.find()))
df_ratings = pd.DataFrame(list(db.ratings.find()))

### The most rated movie by each age group (based on MovieID with at least 50 ratings)

In [75]:
# Step 1: Overall average rating:
overall_avg = db.ratings.aggregate([
    {
        "$group": {
            "_id": None,
            "avg": { "$avg": "$Rating" }
        }
    }
])
overall_avg = round(list(overall_avg)[0]["avg"], 2)
print(f"🎯 Overall average rating: {overall_avg}")

🎯 Overall average rating: 3.53

In [91]:
pipeline_most_rated_by_age_group = [
    {
        "$lookup": {
            "from": "users",
            "localField": "UserID",
            "foreignField": "UserID",
            "as": "user"
        }
    },
    { "$unwind": "$user" },
    {
        "$addFields": {
            "AgeGroup": {
                "$multiply": [
                    { "$floor": { "$divide": [ "$user.Age", 10 ] } },
                    10
                ]
            }
        }
    },
    {
        "$group": {
            "_id": { "AgeGroup": "$AgeGroup", "ItemID": "$ItemID" },
            "count": { "$sum": 1 },
            "avgRating": { "$avg": "$Rating" }
        }
    },
    # with at least 50 ratings
    {
        "$match": { "count": { "$gte": 50 } }
    },
    {
        "$sort": {
            "_id.AgeGroup": 1,
            "count": -1
        }
    },
    {
        "$group": {
            "_id": "$_id.AgeGroup",
            "TopMovieID": { "$first": "$_id.ItemID" },
            "count": { "$first": "$count" },
            "avgRating": { "$first": "$avgRating" }
        }
    },
    {
        "$lookup": {
            "from": "movies",
            "localField": "TopMovieID",
            "foreignField": "Movie_Id",
            "as": "movie"
        }
    },
    { "$unwind": "$movie" },
    {
        "$addFields": {
            "avgRating": { "$round": ["$avgRating", 2] },
            "diffFromOverall": {
                "$round": [
                    { "$subtract": ["$avgRating", overall_avg] },
                    2
                ]
            }
        }
    },
    {
       "$project": {
        "_id": 0,
        "AgeGroup": "$_id",
        "MovieID": "$TopMovieID",
        "Title": "$movie.Movie_Title",
        "count": 1,
        "avgRating": 1,
        "diffFromOverall": 1
       }
    },
    {
        "$sort": { "AgeGroup": 1 }
    }
]

In [87]:
result = list(db.ratings.aggregate(pipeline_most_rated_by_age_group))

import pandas as pd
df = pd.DataFrame(result)

print("✅ Most rated movie by each age group (with ≥50 ratings):")
print(df)

✅ Most rated movie by each age group (with ≥50 ratings):
   count  avgRating  diffFromOverall  AgeGroup  MovieID  \
0     65       3.78             0.25      10.0      288
1    230       4.41             0.88      20.0       50
2    157       4.31             0.78      30.0       50
3    104       3.63             0.10      40.0      286
4     71       3.77             0.24      50.0      286

                         Title
0                Scream (1996)
1             Star Wars (1977)
2             Star Wars (1977)
3  English Patient, The (1996)
4  English Patient, The (1996)

### Average rating for each movie genre

In [93]:
genre_list = [
    "Action", "Adventure", "Animation", "Children", "Comedy", "Crime",
    "Documentary", "Drama", "Fantasy", "Film-Noir", "Horror", "Musical",
    "Mystery", "Romance", "Sci-Fi", "Thriller", "War", "Western"
]

# Create facet structure
genre_facets = {
    genre: [
        {
            "$lookup": {
                "from": "movies",
                "localField": "ItemID",
                "foreignField": "Movie_Id",
                "as": "movie"
            }
        },
        { "$unwind": "$movie" },
        { "$match": { f"movie.{genre}": 1 } },
        {
            "$group": {
                "_id": None,
                "avgRating": { "$avg": "$Rating" },
                "count": { "$sum": 1 }
            }
        },
        {
            "$project": {
                "_id": 0,
                "Genre": genre,
                "avgRating": 1,
                "count": 1
            }
        }
    ]
    for genre in genre_list
}

pipeline_avg_by_genre_sample = [
    { "$facet": genre_facets },
    {
        "$project": {
            "combined": {
                "$concatArrays": [f"${g}" for g in genre_list]
            }
        }
    },
    { "$unwind": "$combined" },
    { "$replaceRoot": { "newRoot": "$combined" } },
    { "$sort": { "avgRating": -1 } }
]



result2 = list(db.ratings.aggregate(pipeline_avg_by_genre))
df_avg_genre = pd.DataFrame(result2)
df_avg_genre.rename(columns={"_id": "Genre"}, inplace=True)
print("✅ Average rating for each movie genre：")
print(df_avg_genre)

✅ Average rating for each movie genre：
    avgRating  count        Genre
0    3.921523   1733    Film-Noir
1    3.815812   9398          War
2    3.687379  39895        Drama
3    3.672823    758  Documentary
4    3.638132   5245      Mystery
5    3.632278   8055        Crime
6    3.621705  19461      Romance
7    3.613269   1854      Western
8    3.576699   3605    Animation
9    3.560723  12730       Sci-Fi
10   3.521397   4954      Musical
11   3.509007  21872     Thriller
12   3.503527  13753    Adventure
13   3.480245  25589       Action
14   3.394073  29832       Comedy
15   3.353244   7182     Children
16   3.290389   5317       Horror
17   3.215237   1352      Fantasy

### Top 10 highest-rated movies (with at least 50 ratings)

In [59]:
pipeline_top10_movies = [
    {
        "$group": {
            "_id": "$ItemID",
            "avgRating": { "$avg": "$Rating" },
            "count": { "$sum": 1 }
        }
    },
    { "$match": { "count": { "$gte": 50 } } },
    { "$sort": { "avgRating": -1 } },
    { "$limit": 10 },
    {
        "$lookup": {
            "from": "movies",
            "localField": "_id",
            "foreignField": "Movie_Id",
            "as": "movie"
        }
    },
    { "$unwind": "$movie" },
    {
        "$project": {
            "_id": 0,
            "MovieID": "$_id",
            "Title": "$movie.Movie_Title",
            "avgRating": 1,
            "count": 1
        }
    }
]


result3 = list(db.ratings.aggregate(pipeline_top10_movies))
df_top10 = pd.DataFrame(result3)

print("✅ Top 10 highest-rated movies (with at least 50 ratings):")
print(df_top10)

✅ Top 10 highest-rated movies (with at least 50 ratings):
   avgRating  count  MovieID  \
0   4.491071    112      408
1   4.466443    298      318
2   4.466102    118      169
3   4.456790    243      483
4   4.447761     67      114
5   4.445230    283       64
6   4.387560    209      603
7   4.385768    267       12
8   4.358491    583       50
9   4.344000    125      178

                                               Title
0                              Close Shave, A (1995)
1                            Schindler's List (1993)
2                         Wrong Trousers, The (1993)
3                                  Casablanca (1942)
4  Wallace & Gromit: The Best of Aardman Animatio...
5                   Shawshank Redemption, The (1994)
6                                 Rear Window (1954)
7                         Usual Suspects, The (1995)
8                                   Star Wars (1977)
9                                12 Angry Men (1957)